---
output:
  bookdown::html_document2: default
  bookdown::pdf_document2:
    template: templates/template.tex
  bookdown::word_document2: default
documentclass: book


#bibliography: [bibliography/references.bib, bibliography/additional-references.bib]
---

<style>
body {
text-align: justify}
</style>

# Introduction {.unnumbered}

```{=tex}
\adjustmtc
\markboth{Introduction}{}
```
<!-- For PDF output, include these two LaTeX commands after unnumbered chapter headings, otherwise the mini table of contents and the running header will show the previous chapter -->

Personalised Healthcare Education is needed to meet growing demand and quality maintenance. There is growing evidence around chatbots, namely machine conversation systems- these programs have the potential to change the way students learn and search for information.
Chatbots can quiz existing knowledge, enable higher student engagement with a learning task, or support higher-order cognitive activities. In large-scale learning scenarios with a high student-to-lecturer ratio, chatbots can help tackle the issue of individualized student support and facilitate personalized learning. However, limited examples of chatbots in European Healthcare Curricula have been utilized to combine both the continuum of cognitive processes presented in Bloom’s taxonomy, with the idea that some repetitive tasks can be done with a chatbot- to provide greater access or to scale faculty time.
Thus, CEPEH strategic partnership has co-created open access chatbots utilizing artiﬁcial intelligence, promoting innovative practices in digital era, by supporting current curricula and fostering open education.
CEPEH Erasmus+ strategic partnership aimed to co-design and implement new pedagogical approaches and, in particular, chatbots for European medical and nursing schools. CEPEH used use participatory design to engage stakeholders (students, healthcare workforce staﬀ, lecturers, clinicians, etc.) in order to co-design eﬀective chatbots and release them as open access resources. Through CEPEH, eﬀective use of digital technologies and open education were be incorporated into healthcare curricula. This enabled students to increase their health and medical related skills through ﬂexible learning.

CEPEH expected that students adopted this new digital pedagogy and im- prove their skills and competences through ﬂexible personalized learning, while the teaching staﬀ enhanced their e-learning tool co-creation competences and make use of co-design best practices and recommendations for use. It is also expected increased cooperation between the partners. Thus, in the long term, CEPEH expects to inﬂuence the development of medical and nursing curricula with this digital innovation, foster the quality of the future healthcare workforce and further improve international competitiveness of the partners’ healthcare curricula. This document details the evaluation of the resources created by the CEPEH team.
The evaluation speciﬁcally explored the feasibility and acceptance from the end-users. These end-users are learners in European healthcare higher education institutions.

  
There was ﬁrstly evidence for the need to identify the feasibility of chatbots and similar resources into formal education and training, with a further need to improve access to these types of learning resources. Of course, studies exist on the acceptance of chatbots, virtual patients, and many other healthcare applications, with promising results. However, through various limitations, we believed there was further research to be completed to accelerate the design, development, implementation, and evaluation processes. These have ﬁnancial, stakeholder, time, and eﬃcacy beneﬁts. The creation process of CEPEH resources was signiﬁcantly diﬀerent to most in the literature, and this report highlights the approach of the CEPEH team towards enhancing personalized healthcare education can be achieved.



## Background {#sec-background .unnumbered}

The working practices of CEPEH are aimed at maximizing efficacy of these chatbots as learning resources, and provided a sense of shared development and ownership from all stakeholders. The process normally begins with workshops in which the project is scoped, and team building occurs. The CEPEH workshops involve the widest possible team of stakeholders including tutors, students, healthcare workers, learning technologists, health service users and carers- depending on the materials being created.  For readers who are interested in using these high quality digital resources please access them for free at CEPEH.EU. The next section will now present the evaluation of all CEPEH chatbot resources.
